theme: minima
title: Your awesome title
author: TheLemon
email: theemailofalemon@lemonmail.lemon
description: > # this means to ignore newlines until "baseurl:"
  This description will likely be significantly less awesome that the expectations that were 
  set by the previous, in-built description. Well, hopefully this isn't too disappointing
  as a description, despite the fact that it hasn't actually described anything... You know, 
  this therefore isn't even technically a description. Thanks for reading this block of utterly
  useless text, if you have, for whatever reason actually decided to do that :)

# social links
twitter_username: Twitter? What was that again? The one with the bird, right? # DO NOT include the @ character, or else the build will fail!
github_username:  lemon-gith # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
